MD001: false
MD003:
  style: 'atx'
MD004:
  style: 'dash'
MD007:
  indent: 2
MD009: false
MD012: false
MD013: false
MD019: false

MD033: false # Allow raw HTML (needed for MkDocs extensions)
MD034: false # Allow inline HTML
MD036: false
MD037: false

MD024:
  allow_different_nesting: true

MD040: false
MD041: false
extends: []
ignores:
  - 'node_modules/**'
  - '.venv/**'
  - 'site/**'
  - '**/.git/**'
  - '**/CHANGELOG.md'
  - '**/README.md'
  - 'tests/**/*.md'

MD025: false # Multiple top-level headers (allow in docs)
MD026: false # Trailing punctuation in headers
MD029: # Ordered list item prefix
  style: 'ordered'
