site_name: DRUIDS Wiki
site_description: Democratic Revolutionary Unified Information & Documentation System
site_author: KS Socialist Book Club
site_url: https://druids.kssocialistbookclub.com

# Repository
repo_name: ks-sbc/DRUIDS
repo_url: https://github.com/ks-sbc/DRUIDS
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicons/favicon.ico
  logo: assets/images/logo.svg
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

plugins:
  - search
  # - pub-debugger:
  #     console_log:
  #       enabled: true
  #       log_level: DEBUGGER
  #     file_log:
  #       enabled: TRUE
  #     zip_log:
  #       enabled: TRUE
  - pub-obsidian:
      obsidian_dir: .obsidian
      templates_dir: _templates
      backlinks:
        enabled: true
      callouts:
        enabled: true
        indentation: spaces
      comments:
        enabled: false
      links:
        wikilinks_enabled: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      timezone: UTC
      locale: en
      fallback_to_build_date: false
  - tags

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true
      title: On this page
      toc_depth: 2-3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: yourusername
      repo: your-repo
  - pymdownx.critic
  - pymdownx.saneheaders

# Navigation - Revolutionary User Journey
nav:
  - Home: index.md
  - Democratic Centralism: democratic-centralism.md
  - Getting Started: getting-started.md
  - Start Your Journey:
      - Overview: start/index.md
      - Why DRUIDS?: start/why-druids.md
      - Quick Demo: start/quick-demo.md
      - Onboarding Guide: start/onboarding-yourself-in-3-days.md
  - Learn:
      - Learning Path: learn/index.md
      - Git Learning Path: learn/git-learning-path.md
      - Glossary: learn/glossary.md
      - Visual Roadmaps: learn/visual-roadmaps.md
      - Core Concepts:
          - Overview: learn/core-concepts/index.md
          - Institutional Memory: learn/core-concepts/institutional-memory.md
          - Democratic Centralism: learn/core-concepts/democratic-centralism.md
          - Security as Practice: learn/core-concepts/security-as-revolutionary-practice.md
          - DRUIDS Security: learn/core-concepts/druids-security-implementation.md
          - Tech Democratization: learn/core-concepts/tech-democratization-as-class-struggle.md
          - Anti-Pattern Framework: learn/core-concepts/anti-pattern-framework.md
          - Power Steering Metaphor: learn/core-concepts/power-steering-metaphor.md
          - Three Tier System: learn/core-concepts/three-tier-system.md
          - Tukhachevsky Bridge: learn/core-concepts/tukhachevsky-bridge.md
      - Git Fundamentals:
          - Overview: learn/git-basics/index.md
          - Why Git?: learn/git-basics/why-revolutionaries-need-git.md
          - Demystifying Git: learn/git-basics/git-isnt-programming.md
          - Learn Through Campaign: learn/git-basics/git-through-campaign.md
          - Essential Commands: learn/git-basics/git-in-7-commands.md
          - Daily Workflows: learn/git-basics/daily-git-workflows.md
          - Command Reference: implement/git/git-command-reference-card.md
          - Quick Reference: implement/git/git-quick-reference.md
          - Visual Workflows: learn/git-basics/visual-git-workflows.md
      - DRUIDS Fundamentals:
          - Overview: learn/druids-fundamentals/index.md
          - Commit Conventions: learn/druids-fundamentals/revolutionary-commit-conventions.md
          - Democratic Code Review: learn/druids-fundamentals/democratic-centralism-code-review.md
          - Red Lines: learn/druids-fundamentals/druids-red-lines.md
          - Federation Protocols: learn/druids-fundamentals/federation-protocols.md
          - Obsidian Integration: learn/druids-fundamentals/obsidian-integration.md
          - Philosophy: learn/druids-fundamentals/philosophy.md
      - Explanations:
          - Overview: learn/explanations/index.md
          - Google Drive Trap: learn/explanations/google-drive-trap.md
          - Role of AI: learn/explanations/role-of-ai.md
          - Signal Isn't Enough: learn/explanations/signal-isnt-enough.md
          - State Repression: learn/explanations/state-repression.md
          - Why Discord Democracy Fails: learn/explanations/why-discord-democracy-fails.md
          - Institutional Memory: learn/explanations/institutional-memory-and-onboarding.md
      - Design:
          - Quantum Matter Accessibility: learn/design/qm-accessibility.md
      - MkDocs:
          - Overview: learn/mkdocs/index.md
          - MkDocs Guide: learn/mkdocs/mkdocs.md
      - Website:
          - Overview: website/index.md
          - Customization Guide: website/customization-guide.md
          - Features Demo: website/features-demo.md
          - Navigation Guide: website/navigation-guide.md
          - Quick Reference: website/quick-reference.md
          - Tags: website/tags.md
          - Typography: website/typography.md
          - Design:
              - Overview: website/design/index.md
              - Components: website/design/components.md
          - Features:
              - Overview: website/features/index.md
              - Versioning: website/features/versioning-guide.md
          - Blog:
              - Overview: website/blog/index.md
              - Advanced Navigation: website/blog/advanced-navigation-techniques.md
              - Building Community: website/blog/building-engaged-community.md
              - MkDocs Features: website/blog/mkdocs-material-features.md
              - Welcome Post: website/blog/welcome-to-our-blog.md
          - Reference:
              - Overview: website/reference/index.md
              - Configuration: website/reference/configuration-reference.md
      - Tutorials:
          - Escaping Google Surveillance: learn/tutorials/escaping-google-surveillance.md
          - Onboarding Without Burnout: learn/tutorials/onboarding-without-burnout.md
          - Your First Revolutionary Commit: learn/tutorials/your-first-revolutionary-commit.md
  - How-To:
      - Test Suite Usage: how-to/test-suite-usage.md
      - Breaking Discord Chains: how-to/breaking-discord-chains.md
      - Project Commands Usage: how-to/project-commands-usage.md
      - Pseudonym Discipline: how-to/pseudonym-discipline.md
  - Implement:
      - Implementation Guide: implement/index.md
      - Getting Started:
          - Installation: implement/getting-started/druids-installation-guide.md
          - Migration Guides:
              - From Discord: implement/getting-started/migration-guides/from-discord.md
              - From Google: implement/getting-started/migration-guides/from-google-docs.md
              - Escaping Google Surveillance: guides/migration/escaping-google-surveillance.md
      - Advanced:
          - Custom Tails: implement/advanced/custom-tails-image-technical-guide.md
          - Tails Deployment: implement/advanced/druids-tails-deployment.md
          - Bootstrap Scripts: implement/advanced/druids-tails-bootstrap-scripts.md
      - Obsidian Setup:
          - Overview: implement/obsidian-setup/_index.md
          - Complete Setup Guide: implement/obsidian-setup/complete-setup-guide.md
          - Commit Signing with GPG: implement/obsidian-setup/commit-signing-gpg-hardware-keys.md
          - Automatic Commits: implement/obsidian-setup/configuring-automatic-commits.md
          - Merge Conflicts: implement/obsidian-setup/handling-merge-conflicts.md
          - Merge Request Process: implement/obsidian-setup/merge-request-process.md
          - Git Workflow Guide: implement/obsidian-setup/obsidian-git-workflow-guide.md
          - Offline Git Workflow: implement/obsidian-setup/obsidian-offline-git-workflow-guide.md
          - PR Workflow: implement/obsidian-setup/pr-workflow.md
      - Security:
          - Overview: implement/security/index.md
          - Git History Scrubbing: implement/security/git-history-scrubbing.md
          - Committed Sensitive Data: implement/security/help-committed-sensitive-data.md
          - Metadata Stripping: implement/security/metadata-stripping-pipeline.md
          - Security Audits: implement/security/security-audits-for-organizers.md
          - Security Playbook: implement/security/security-playbook.md
          - When They Come Knocking: implement/security/when-they-come-knocking.md
      - Workflows:
          - Overview: implement/workflows/index.md
          - Bus Factor Elimination: implement/workflows/bus-factor-elimination.md
          - Git Workflow Guide: implement/workflows/git-workflow-guide.md
          - Git Workflows by Role: implement/workflows/git-workflows-by-role.md
          - Meeting Workflow: implement/workflows/meeting-workflow-guide.md
          - Project Management: implement/workflows/project-management-guide.md
          - Proposal Process: implement/workflows/proposal-process.md
          - Task Management: implement/workflows/task-management.md
      - Git Reference:
          - Command Reference: implement/git/git-command-reference-card.md
          - Quick Reference: implement/git/git-quick-reference.md
      - MkDocs Implementation:
          - Setup Giscus: implement/mkdocs/setup-giscus.md
          - Configuration Reference: implement/mkdocs/configuration-reference.md
          - Analytics Privacy: implement/mkdocs/analytics-privacy-guide.md
          - Offline Usage: implement/mkdocs/offline-usage-guide.md
          - Website Validations: implement/mkdocs/website-validations.md
          - CSS Reference: implement/mkdocs/css.md
      - Design Implementation:
          - QM Implementation Guide: implement/design/qm-implementation-guide.md
          - QM Troubleshooting: implement/design/qm-troubleshooting.md
          - Theme Development: implement/design/theme-development-guide.md
  - Teach:
      - Teaching Guide: teach/index.md
      - Democratize Tech: teach/teach-tech-without-priest-hood.md
      - Workshops:
          - Overview: teach/workshops/index.md
          - Git Through Campaign: teach/workshops/git-through-campaign-template.md
          - Git Through Campaign Guide: teach/workshops/git-through-campaign.md
  - Reference:
      - Overview: reference/index.md
      - Glossary: reference/glossary.md
      - Testing:
          - Test Suite Reference: reference/testing/test-suite-reference.md
      - Templates:
          - Meeting Minutes: _templates/meeting-minutes-template.md
          - Proposals: _templates/proposal-template.md
          - Security Incidents: _templates/security-incident-template.md
  - Contributing:
      - Style Guide: contributing/revolutionary-style-guide.md
      - Cross-Reference Guide: contributing/cross-reference-guide.md
  - Test Features: test-features.md
  - Test Features Results: test-features-results.md
  - Test Giscus: test-giscus.md
  - Privacy Policy: privacy-policy.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ks-sbc
      name: GitHub
  comments:
    provider: giscus
    repo: ks-sbc/DRUIDS
    repo_id: R_kgDOOsxCLA
    category: General
    category_id: DIC_kwDOOsxCLM4CsOJY
    mapping: pathname
    strict: 0
    reactions: 1
    emit_metadata: 0
    input_position: top
    theme: dark_high_contrast
    lang: en
    loading: lazy

# extra_css:
#   - assets/css/druids-theme.css
#   - assets/css/druids-layout.css
#   - assets/css/druids-components.css
#   - assets/css/druids-utilities.css

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/giscus.js
  - assets/js/search.js
