site_name: DRUIDS Wiki
site_description: Democratic Revolutionary Unified Information & Documentation System
site_author: KS Socialist Book Club
site_url: https://druids.kssocialistbookclub.com

# Repository
repo_name: ks-sbc/DRUIDS
repo_url: https://github.com/ks-sbc/DRUIDS
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicons/favicon.ico
  logo: assets/images/logo.svg
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

plugins:
  - search
  - pub-debugger:
      console_log:
        enabled: true
        log_level: INFO
      file_log:
        enabled: false
      zip_log:
        enabled: false
  - pub-obsidian:
      obsidian_dir: .obsidian
      templates_dir: _templates
      backlinks:
        enabled: true
      callouts:
        enabled: true
        indentation: spaces
      comments:
        enabled: false
      links:
        wikilinks_enabled: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      timezone: UTC
      locale: en
      fallback_to_build_date: false
  - tags

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: yourusername
      repo: your-repo
  - pymdownx.critic
  - pymdownx.saneheaders

# Navigation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Test Features: test-features.md
  - Test Giscus: test-giscus.md
  - Blog: blog/index.md
  - Tutorials:
      - Overview: tutorials/index.md
      - Customization Guide: tutorials/customization-guide.md
      - Website Validations: tutorials/website-validations.md
  - How-To Guides:
      - MkDocs Setup: how-to/mkdocs.md
      - Giscus Setup: setup-giscus.md
  - Reference:
      - Overview: reference/index.md
      - Website Features:
          - Analytics & Privacy: reference/website/analytics-privacy-guide.md
          - Feature Demo: reference/website/features-demo.md
          - Navigation Guide: reference/website/navigation-guide.md
          - Offline Usage: reference/website/offline-usage-guide.md
          - Tags: reference/website/tags.md
          - Versioning: reference/website/versioning-guide.md
  - Feature Demo: features-demo.md
  - Customization Guide: customization-guide.md
  - Tags: tags.md
  - Privacy Policy: privacy-policy.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ks-sbc
      name: GitHub
  comments:
    provider: giscus
    repo: ks-sbc/DRUIDS
    repo_id: R_kgDOOsxCLA
    category: General
    category_id: DIC_kwDOOsxCLM4CsOJY
    mapping: pathname
    strict: 0
    reactions: 1
    emit_metadata: 0
    input_position: top
    theme: dark_high_contrast
    lang: en
    loading: lazy

extra_css:
  - assets/css/druids-theme.css
  - assets/css/druids-layout.css
  - assets/css/druids-components.css
  - assets/css/druids-utilities.css

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/giscus.js
  - assets/js/search.js
